export type MapTile = {
  type: "empty" | "wall" | "ally" | "enemy" | "noManLand";
  position?: number;
};

export const mapLayout: MapTile[][] = [
  [
    { type: "empty" },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "empty" },
  ],
  [
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
  ],
  [
    { type: "empty" },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "empty" },
  ],
  [
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
  ],

  [
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
  ],
  [
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
  ],

  [
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
  ],
  [
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
    { type: "enemy", position: 1 },
    { type: "empty" },
  ],

  [
    { type: "noManLand" },
    { type: "empty" },
    { type: "noManLand" },
    { type: "empty" },
    { type: "noManLand" },
    { type: "empty" },
    { type: "noManLand" },
  ],
  [
    { type: "empty" },
    { type: "noManLand" },
    { type: "empty" },
    { type: "ally", position: 13 },
    { type: "empty" },
    { type: "noManLand" },
    { type: "empty" },
  ],

  [
    { type: "noManLand" },
    { type: "empty" },
    { type: "ally", position: 12 },
    { type: "empty" },
    { type: "ally", position: 11 },
    { type: "empty" },
    { type: "noManLand" },
  ],
  [
    { type: "empty" },
    { type: "ally", position: 10 },
    { type: "empty" },
    { type: "ally", position: 9 },
    { type: "empty" },
    { type: "ally", position: 8 },
    { type: "empty" },
  ],

  [
    { type: "empty" },
    { type: "empty" },
    { type: "ally", position: 7 },
    { type: "empty" },
    { type: "ally", position: 6 },
    { type: "empty" },
    { type: "empty" },
  ],
  [
    { type: "empty" },
    { type: "ally", position: 5 },
    { type: "empty" },
    { type: "ally", position: 4 },
    { type: "empty" },
    { type: "ally", position: 3 },
    { type: "empty" },
  ],
  [
    { type: "empty" },
    { type: "empty" },
    { type: "ally", position: 2 },
    { type: "empty" },
    { type: "ally", position: 1 },
    { type: "empty" },
    { type: "empty" },
  ],
];
